version: '2'
services:
    web:
        build: .
        ports:
            - "80:9000"
        depends_on:
            - postgres
        environment:
            STAGE: 'development'
            POSTGRES_ADDRESS: postgres
            POSTGRES_PASSWORD: map-api
            POSTGRES_USER: map-api
            POSTGRES_DB: map-api
            SENTRY_DSN: ''

    postgres:
        image: 'mdillon/postgis:9.5'
        ports:
            - "9001:5432"
        environment:
            POSTGRES_PASSWORD: map-api
            POSTGRES_USER: map-api
            POSTGRES_DB: map-api

    pgadmin:
        image: 'dpage/pgadmin4'
        ports:
            - "9002:80"
        environment:
            POSTGRES_PASSWORD: map-api
            POSTGRES_USER: map-api
            POSTGRES_DB: map-api
